wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1650394774
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 14
      4: 3.10.4
      5: 0.12.12
      8:
      - 3
      - 5
