wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.3
    start_time: 1649174629
    t:
      3:
      - 19
      4: 3.10.3
      5: 0.12.11
      8:
      - 3
      - 5
version:
  desc: null
  value: fp-base
